name: Build Gradle bundle, container image and push to Git registry

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  BUNDLE_VERSION: 0.0.2-SNAPSHOT
  JDK_VERSION: 17
  NODE_VERSION: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '${{env.NODE_VERSION}}'
    - name: Install dependencies
      run: npm install
      working-directory: ui/ui-vue
    - run: npm run build
      working-directory: ui/ui-vue
    - name: Set up JDK ${{env.JDK_VERSION}}
      uses: actions/setup-java@v3
      with:
        java-version: '${{env.JDK_VERSION}}'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Execute Gradle build
      run: ./gradlew build
      working-directory: rest-service-kotlin/

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the image to Github registry
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/rest-service:${{ env.BUNDLE_VERSION }}
        file: rest-service-kotlin/Dockerfile
        context: .
        no-cache: true
        build-args: |
          bundle_path=rest-service-kotlin/build/libs/rest-service-${{ env.BUNDLE_VERSION }}.jar